services:
  - type: web
    name: dressify-backend
    runtime: python
    plan: free
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: dressify-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npx vite build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false